### ISSUE TITLE
Dropping cached image in IndexedDB storage and rebuild image

### ISSUE THREAD

**Issue by darrellpruitt** [FreshVine/jQuery-cache-images#10]
I'm sure I am not understanding something correctly but I am having a little trouble dropping a cached image and then causing it to be re-cached with an updated image. I am using the IndexedDB storage. I execute "$.fn.cacheImages.drop" to drop a specific image and then want to re-cache an updated image. The drop appears to be working ok according to the "Resources" tab in Chrome but the re-cache of the image seems to be finding an image already cached. What am I doing wrong? The following is my code:

$.fn.cacheImages.drop(v_charturlactuals, v_storagePrefix);
$('.summarychartimgactuals'+obj.SUMMARY_TESTNUM_ID).cacheImages( {storagePrefix: v_storagePrefix, url: v_charturlactuals} );

I appreciate your help and patience if this is a dumb question.

**Comment by paulprins** [comment]
@darrellpruitt yea you weren't doing anything wrong. the issue is that the drop function didn't have a callback, and thats why you were having issues. IndexDB is not a functional call (it breaks out of the line by line flow you're expecting with your javascript). I just updated the script adn you should be able to do this now one of two ways.

Using the callback for the drop script:

    $.fn.cacheImages.drop(v_charturlactuals, function(){ 
        $('.summarychartimgactuals'+obj.SUMMARY_TESTNUM_ID).cacheImages( {storagePrefix: v_storagePrefix, url: v_charturlactuals} );
    },  v_storagePrefix);

Or, even more simply with the forceSave option just added.

    $('.summarychartimgactuals'+obj.SUMMARY_TESTNUM_ID).cacheImages( {storagePrefix: v_storagePrefix, url: v_charturlactuals, forceSave: true });

Be careful with the forceSave though. If you always use it the plugin is pretty pointless as it will always fetch a new image. In an ideal world where you control the media you're fetching from the remote server you shouldn't reuse the same filenames (keeps browsers/third-party from caching) but either of these options should work for ya.

**Comment by darrellpruitt** [comment]
Thank you!  Very much appreciated!

Darrell

**Comment by darrellpruitt** [comment]
I had to make one change to your code. I was getting a javascript error “thisElem is not defined” for the line:

callbackFunction.call(thisElem, key, encodedString );

Since I didn’t need those variables in my callback I changed it to the following and it worked great:

callbackFunction.call( );

Darrell

From: Darrell Pruitt
Sent: Wednesday, October 07, 2015 1:35 PM
To: 'FreshVine/jQuery-cache-images'; FreshVine/jQuery-cache-images
Subject: RE: [jQuery-cache-images] Dropping cached image in IndexedDB storage and rebuild image (#10)

Thank you!  Very much appreciated!

Darrell

**Comment by paulprins** [comment]
Good call @darrellpruitt - I also made that fix, but instead of no params it now reads

    callbackFunction.call( url );

**Comment by darrellpruitt** [comment]
Perfect! Thanks!

Darrell

**Comment by paulprins** [comment]
Awesome, glad that it's working for ya!
